hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("~/.config/hypr/scripts/lid-close-lock.sh")
  hl.exec_cmd("eww daemon")
  hl.exec_cmd("eww open --config ~/.config/eww/bar/ bar")
  hl.exec_cmd("~/.config/eww/bar/assets/key_logger.sh")
  hl.exec_cmd("mako")
  hl.exec_cmd("kitty +kitten panel --edge=background -o font_size=16 -o background_opacity=0 cava -p ~/.config/cava/background_config")
  hl.exec_cmd(Browser, { workspace = "2 silent" })
  hl.exec_cmd("lutris", { workspace = "3 silent" })
  hl.exec_cmd(MediaPlayer, { workspace = "9 silent" })
  hl.exec_cmd(MusicPlayer, { workspace = "10 silent" })
end)
